### ISSUE TITLE
OSError: [WinError 10014] 系统检测到在一个调用中尝试使用指针参数时的无效指针地址。

### ISSUE THREAD

**Issue by SDchao** [richardchien/coolq-http-api#280]
在参考NoneBot教程中 开始使用一节 时，运行出现以下错误：
```
[2020-01-27 16:20:53,008 nonebot] INFO: Succeeded to import "nonebot.plugins.base"
[2020-01-27 16:20:53,010 nonebot] INFO: Running on 127.0.0.1:8081
Running on http://127.0.0.1:8081 (CTRL + C to quit)
[2020-01-27 16:20:53,018] Running on 127.0.0.1:8081 over http (CTRL + C to quit)
Accept failed on a socket
socket: <asyncio.TransportSocket fd=920, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 8081)>
Traceback (most recent call last):
  File "D:\SDK\Python\lib\asyncio\proactor_events.py", line 801, in loop
    conn, addr = f.result()
  File "D:\SDK\Python\lib\asyncio\windows_events.py", line 808, in _poll
    value = callback(transferred, key, ov)
  File "D:\SDK\Python\lib\asyncio\windows_events.py", line 557, in finish_accept
    return conn, conn.getpeername()
OSError: [WinError 10014] 系统检测到在一个调用中尝试使用指针参数时的无效指针地址。
Task exception was never retrieved
future: <Task finished name='Task-7' coro=<IocpProactor.accept.<locals>.accept_coro() done, defined at D:\SDK\Python\lib\asyncio\windows_events.py:559> exception=OSError(10014, '系统检测到在一个调用中 
尝试使用指针参数时的无效指针地址。', None, 10014, None)>
Traceback (most recent call last):
  File "D:\SDK\Python\lib\asyncio\windows_events.py", line 562, in accept_coro
    await future
  File "D:\SDK\Python\lib\asyncio\proactor_events.py", line 801, in loop
    conn, addr = f.result()
  File "D:\SDK\Python\lib\asyncio\windows_events.py", line 808, in _poll
    value = callback(transferred, key, ov)
  File "D:\SDK\Python\lib\asyncio\windows_events.py", line 557, in finish_accept
    return conn, conn.getpeername()
OSError: [WinError 10014] 系统检测到在一个调用中尝试使用指针参数时的无效指针地址。
```

以下为bot.py
```
import nonebot

if __name__ == "__main__" :
    nonebot.init()
    nonebot.load_builtin_plugins()
    nonebot.run(host="127.0.0.1", port=8081)
```

以下为CQHTTP配置
```
{
    "host": "[::]",
    "port": 5700,
    "use_http": true,
    "ws_host": "[::]",
    "ws_port": 6700,
    "use_ws": false,
    "ws_reverse_url": "",
    "ws_reverse_api_url": "ws://127.0.0.1:8081/ws/api/",
    "ws_reverse_event_url": "ws://127.0.0.1:8081/ws/event/",
    "ws_reverse_reconnect_interval": 3000,
    "ws_reverse_reconnect_on_code_1000": true,
    "use_ws_reverse": true,
    "post_url": "",
    "access_token": "",
    "secret": "",
    "post_message_format": "string",
    "serve_data_files": false,
    "update_source": "china",
    "update_channel": "stable",
    "auto_check_update": false,
    "auto_perform_update": false,
    "show_log_console": true,
    "log_level": "info"
}
```
CQHTTP  控制台重复显示
```
[2020-01-27 16:22:27.349] [I] [反向WS] 开启反向 WebSocket 客户端（API）成功，开始连接 ws://127.0.0.1:8081/ws/api/
[2020-01-27 16:22:29.355] [W] [反向WS] 反向 WebSocket（API）客户端连接失败或异常断开，将在 3000 毫秒后尝试重连
```

希望可以帮忙解决一下，万分感谢ww

**Comment by richardchien** [comment]
你用的是 Python 3.8 吗

**Comment by SDchao** [comment]
> 你用的是 Python 3.8 吗

是的

**Comment by richardchien** [comment]
我今晚可能会升级一下 NoneBot 的依赖版本，到时候会解决

如果急用的话，可以先试试换到 Python 3.7

**Comment by SDchao** [comment]
> 我今晚可能会升级一下 NoneBot 的依赖版本，到时候会解决
> 
> 如果急用的话，可以先试试换到 Python 3.7

非常感谢！辛苦了！

**Comment by richardchien** [comment]
你试下升级 aiocqhttp 到 0.7.0

```bash
pip install -U aiocqhttp
```
